{% set name = "pydyf" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b44a38855d7e47b740b3cd31ab63a2f5b9b2793931d50b0ccaed3bb7b86912fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - pydyf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.courtbouillon.org/pydyf
  summary: A low-level PDF generator.
  license: BSD-3-Clause
  license_file:
    - LICENSE
  dev_url: https://github.com/CourtBouillon/pydyf
  doc_url: https://doc.courtbouillon.org/pydyf/

extra:
  recipe-maintainers:
    - liZe
    - BastianZim
